language: node_js
node_js:
- node
before_deploy:
- npm run build
deploy:
  provider: npm
  email: vinhpt07@gmail.com
  api_key:
    secure: XR38hRMjOoqXCnKhhgMyFBy+hOpLG6uv2oDfVYCy9yu0Rgq1N30Qy6j51Nxu3T4Tl6aP7RmLD/RPbenMsx1AQTdZ3ZkrnArfXVp3r5jg2buw6pFPpRzCR+RbpWPuduKuWgYCoch8maYmzkw8kGnZK2P1dF042IFr2Qz65I8r06leYTG70iluB5PHdjeRzAzfT5i8Vvtrfm6OZIgKpYslvumo4eHJIheogbduG/pww313KrzWj7OhwCIMTlsNq3L67ZV+s0op3y/XPG7o7CtaK3EdiHwuqSdrU/Idb3sVrIYF/CQDDyN3ttUDRxl8+O9k+LygtjiNNm4JO03dDea3MzWRP9UoHF8m7V+3zuKlWF1a6QHs+RUb60feBqvngLruPzqVEprvupwn/emq1RSTqcPUyK3YVdkh6jhJyaME3N9eQ7s876+zuFTIiZCGlcRvgehVYkuyJWzoD5e6IEF3IFVybNahFnLI5fxLg69xsh0y7kJz3g/OwXtAEyVfy0Zm3i+Cl9wnrbJfLkh/kDIo2mHwMxeTlheL59tXaw7UBtpYVfhZovPlcNRTJOe11w626KsR1jfnHdFzU1lOktVbpMpxa2LDUp6Pjbh7cdLMFE51CyALryzjoguklNjt8Smc9McZdO06LszoAvrkwjrrcp4C7hvRjbJjppLJglJ9GFY=
  on:
    tags: true
    repo: vinhpt07/masks-js
