language: node_js
node_js:
- node
before_deploy:
- npm run build
deploy:
  provider: npm
  email: vinhpt07@gmail.com
  api_key:
    secure: EcXurFYPrTiyep8ynzfFyQ9IsvczFq4GCqtwV+WVQzd4JeOkRGvI+xJLhc2A9+pxbTXvQaz8l7BiqurZ7vzrYsF4U9iJAd2vT3smQ88FuzP+CpTR3Ag5wQu6KcdVAwawuJjLhSqQ9vi7dO2GIcehdhik6hvk7WS2UnDL+hB83mA4TyP7FqV9JH6RUsigzBI+tsgDO/G9AFUq2s1W0mK+G1eysxEtgiRtRIVacJ2LTqIKHSIedEWLn2MJyNzrmaKV6JPnOY/BoUlpaBnfEYKjnkmZ9oblmoIoMBYrEJuG66ke1egtiDDacLQYn5tG0ktkKvAGsJ4oIl5QQWY05I/0kn79dRGvZZGSgJKpwd5c9LQdLlfWcgq71Mv/GoN4MD354mx68+ii3l1CzFt8mNjjXNKyDOavoA/eJF2yQ/C6MZQPBSRmIXeTOliyEepnoQmnhnTKk5BBmMKCtl+bU9+DXQsi8jKcaBPRNbD5XzNo9G8fitU/FGIirknNum4OVTE3ux1hU/N1PXcuqyHb2D9D6zaaAC3D+Dg1pyj/l/2RO+ZDss1aHSBHe28dxuH0BJgUCoSzUBbNFXx+mVuPIOs5edO4xD+lN4yrT/O1gyOI5pThE+LwFF7MHbolI1JssiXRVkPCiX3V7uwd6/qT4Zrg5KefElgBwdb4swplr+neCRc=
  on:
    tags: true
    repo: vinhpt07/masks-js
